version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "prowe-joke-line"
region = "us-east-1"
resolve_s3 = true
s3_prefix = "prowe-joke-line"
on_failure = "DELETE"
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"